use_frameworks!

target 'XMLWriter_Example' do
  pod 'XMLWriter', :path => '../'

  target 'XMLWriter_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
